import { Product } from "../orders/models";

export const demoProducts = [
  {
    id: 1,
    "image": "https://www.bloomable.co.za/Uploads/Images/215a8573-ad89-4cdd-9289-edf315dc8dae.jpg",
    "name": "My Dear",
    "size": "Small - AS SHOWN",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Square Lipped Vase [ Medium]\n1 x Additional Delivery Fee\n2 x Aster [ White]\n3 x Wax [ White]\n3 x Snapdragons [ White]\n5 x Greenery [ Green]\n5 x Roses [ White]",
    "description": "",
  },
  {
    id: 2,
    "image": "https://www.bloomable.co.za/Uploads/Images/f72c1a1f-74ec-4f36-a790-f0d8821ab7a8.jpg",
    "name": "Teddy Bear & Cadbury's Bubbles",
    "size": "Medium",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Teddy Bear [ Medium]\n1 x Cadbury's Bubbly 150g [ 150 g/ml]",
    "description": "",
  },
  {
    id: 3,
    "image": "https://www.bloomable.co.za/Uploads/Images/2fa160fa-4d86-494e-911e-f4d230a134d9.jpg",
    "name": "Get Well Soon Foil Balloon",
    "size": "(Design May Vary)",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Foil Balloon Get Well Soon",
    "description": "Please ensure that FOIL balloons and NOT latex balloons are used.",
  },
  {
    id: 4,
    "image": "https://www.bloomable.co.za/Uploads/Images/92a76e84-4a73-4c51-a908-ff863f30bdc7.jpg",
    "name": "Peachy Pride Bouquet",
    "size": "Small",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Kraft Paper [ Brown]\n1 x Twyne [ Brown]\n1 x Additional Delivery Fee\n2 x Golden Rod [ Yellow]\n2 x Snapdragons [ Orange]\n2 x Gerberas [ Orange]\n2 x Alstromeria [ Orange]\n3 x Roses [ Orange]\n4 x Chrysanthemums [ Orange]\n8 x Greenery [ Green]",
    "description": "Please email care@bloomable.co.za quoting your order number if there are any variations of flowers used in this creation. If the customer is informed of any changes you are more likely to receive better reviews. Thank you. Please ensure 100% customer satisfaction.",
    "extras": [
      {
        "image": "https://www.bloomable.co.za/Uploads/Images/7c7435c9-6ee6-4f13-9b8f-5a4f83fb2301.jpg",
        "name": "Vase White Rose Bouquet",
        "description": "Included in price above (R 280.00)",
      },
    ],
  },
  {
    id: 5,
    "image": "https://www.bloomable.co.za/Uploads/Images/3a2c80b2-598c-4a35-baaf-e2638a8e45b7.jpg",
    "name": "Blushing Boo",
    "size": "Small - AS SHOWN",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Square Glass Vase 12cm X 12cm\n1 x Additional Delivery Fee\n2 x Alstroemeria [ Pink]\n2 x Roses [ Pink]\n2 x Roses [ Red]\n3 x Penny Gum [ Grey]\n4 x Greenery [ Green]",
    "description": "Please email care@bloomable.co.za quoting your order number if there are any variations of flowers used in this creation. If the customer is informed of any changes you are more likely to receive better reviews. Thank you.",
  },
  {
    id: 6,
    "image": "https://www.bloomable.co.za/Uploads/Images/29d3de79-a55f-4914-bc16-bb18369954b4.jpg",
    "name": "Multicoloured Coffin Arrangement",
    "size": "Large - AS SHOWN",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "1 x Rectangle Tray [ Large]\n1 x Additional Delivery Fee\n2 x Oasis [ Medium]\n3 x Delphiniums [ Blue]\n4 x Limonium [ Lilac]\n4 x Viburnum [ Green]\n4 x Umbellatum Lilies [ Orange]\n4 x Lisianthus [ White]\n4 x Gerberas [ Yellow, Small]\n5 x Alstroemeria [ Yellow]\n6 x Large Gerberas [ Yellow]\n10 x Bracken [ Green]\n10 x Greenery [ Green]\n12 x Roses [ Orange]",
    "description": "Dimensions: 130cm x 60cm",
  },
  {
    id: 7,
    "image": "https://www.bloomable.co.za/Uploads/Images/9613454e-68f4-40de-9975-f03810b0b6c1.jpg",
    "name": "Multicoloured Petals AV",
    "size": "Small",
    "quantity": 1,
    "retailPrice": undefined,
    "guidelines": "",
    "description": "",
  },
] as unknown as Product[];
