const today = new Date();

export const demoResponseOrders = {
  "data": [
    {
      "id": "4474",
      "name": "#BLM5296",
      "firstName": "Arthur",
      "lastName": "V. West",
      "phone": "012 345 6789",
      "address1": "201 Xanadu Boulevard,",
      "address2": "Xanadu Nature Estate",
      "city": "Hartebeespoort",
      "country": "South Africa",
      "latitude": -25.7500000,
      "longitude": 27.9100000,
      "created_at": "2023-09-22T18:54:02+00:00",
      "deliveryDate": new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000),
      "lines": [
        {
          "id": 5373,
          "title": "Biltong and Nuts Snack Box - As Shown",
          "status": "accepted",
          "quantity": 1,
          "giftMessage": "Dear Dad\/Grampa Have a wonderful birthday! Lots of love, Simon, Sarah, Kai, Benaiah, & Isaiah ",
          "productVariantId": 822,
          "value": 975,
          "returns": [],
        },
      ],
      "postalCode": "0216",
      "company": null,
      "adjustments": [],
      "status": "accepted",
      "totalValue": 1034.95,
      "notes": null,
      "onPay": 59.95,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4447",
      "name": "#BLM5269",
      "firstName": "",
      "lastName": "Mamelodi branch",
      "phone": "+27 12 345 6789",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.744000,
      "longitude": 28.196000,
      "created_at": "2023-09-22T10:12:26+00:00",
      "deliveryDate": new Date(today.getTime() + 24 * 60 * 60 * 1000),
      "lines": [
        {
          "id": 5343,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "accepted",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
        {
          "id": 5342,
          "title": "OPBAB Rose Petals",
          "status": "accepted",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Nationwide",
      "adjustments": [],
      "status": "accepted",
      "totalValue": 1466.95,
      "notes": "PO: BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4445",
      "name": "#BLM5267",
      "firstName": "",
      "lastName": "Mamelodi branch",
      "phone": "+27 12 345 6489",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.74400,
      "longitude": 28.1960000,
      "created_at": "2023-09-22T10:11:42+00:00",
      "deliveryDate": new Date(today.getTime() + 24 * 60 * 60 * 1000),
      "lines": [
        {
          "id": 5339,
          "title": "OPBAB Rose Petals",
          "status": "accepted",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
        {
          "id": 5340,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "accepted",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Nationwide",
      "adjustments": [],
      "status": "accepted",
      "totalValue": 1466.95,
      "notes": "PO: BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4444",
      "name": "#BLM5266",
      "firstName": "",
      "lastName": "Mamelodi branch",
      "phone": "+27 12 345 6789",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.74400,
      "longitude": 28.1960000,
      "created_at": "2023-09-22T10:10:57+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5337,
          "title": "OPBAB Rose Petals",
          "status": "open",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
        {
          "id": 5338,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "open",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Nationwide",
      "adjustments": [],
      "status": "open",
      "totalValue": 1466.95,
      "notes": "PO: BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4443",
      "name": "#BLM5265",
      "firstName": "",
      "lastName": "Mamelodi branch",
      "phone": "+27 12 345 6789",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.74400,
      "longitude": 28.1960000,
      "created_at": "2023-09-22T10:10:19+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5335,
          "title": "OPBAB Rose Petals",
          "status": "open",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
        {
          "id": 5336,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "open",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Nationwide",
      "adjustments": [],
      "status": "open",
      "totalValue": 1466.95,
      "notes": "PO: BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4422",
      "name": "#BLM5244",
      "firstName": "Alexa",
      "lastName": "Voertsek",
      "phone": "+27123456789",
      "address1": "12 Koeman Street",
      "address2": "melodie",
      "city": "Hartbeespoort",
      "country": "South Africa",
      "latitude": -25.7320000,
      "longitude": 27.8900000,
      "created_at": "2023-09-22T07:18:19+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5313,
          "title": "Colour Me Happy - Large (As Shown) \/ No",
          "status": "accepted",
          "quantity": 1,
          "giftMessage": "Happy Birthday! We love you and hope you have a wonderful birthday.",
          "productVariantId": 577,
          "value": 1285,
          "returns": [],
        },
      ],
      "postalCode": "0216",
      "company": "Kingfisher Village",
      "adjustments": [],
      "status": "accepted",
      "totalValue": 1344.95,
      "notes": null,
      "onPay": 59.95,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4386",
      "name": "#BLM5208",
      "firstName": "Japanesse",
      "lastName": "Sug",
      "phone": "+27 12 345 6789",
      "address1": "123 Pieter street Christoburg",
      "address2": null,
      "city": "Centurion",
      "country": "South Africa",
      "latitude": -25.8040000,
      "longitude": 28.0910000,
      "created_at": "2023-09-21T12:21:54+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5276,
          "title": "Delightful Posy - Small (As Shown)",
          "status": "delivered",
          "quantity": 1,
          "giftMessage": "Nesse :) \r\n\r\nWe wish you a speedy recovery. Feel better soon and take extra good care of yourself !! \r\n\r\nsending you loads and load of hugs and love. \r\n\r\nTeam Typo :) ",
          "productVariantId": 440,
          "value": 530,
          "returns": [],
        },
      ],
      "postalCode": "0183",
      "company": null,
      "adjustments": [],
      "status": "delivered",
      "totalValue": 589.95,
      "notes": null,
      "onPay": 457.45000000000005,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4348",
      "name": "#BLM5170",
      "firstName": "Visvang",
      "lastName": "Terlou",
      "phone": "012 345 6789",
      "address1": "1234 Sakeman Street",
      "address2": "House 1324 Magaliesberg Country Estate Amandasig",
      "city": "Pretoria North",
      "country": "South Africa",
      "latitude": -25.6770000,
      "longitude": 28.0900000,
      "created_at": "2023-09-21T07:39:19+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5235,
          "title": "Country Basket - Medium (As Shown)",
          "status": "fulfilled",
          "quantity": 1,
          "giftMessage": "Dear Vongani \r\nMany caring thoughts and warm wishes are with you as your recover. Hoping to hear you are well again soon!\r\nWith love Think Creative Africa ",
          "productVariantId": 222,
          "value": 805,
          "returns": [],
        },
      ],
      "postalCode": "0182",
      "company": null,
      "adjustments": [],
      "status": "fulfilled",
      "totalValue": 864.95,
      "notes": "Please call Vongani en route to delivery so she can send someone to fetch the flowers for her.",
      "onPay": 663.7,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4346",
      "name": "#BLM5168",
      "firstName": "",
      "lastName": "our driver will come collect the flower",
      "phone": "012 345 6789",
      "address1": "OPBAB mamelodi",
      "address2": null,
      "city": "mamelodi",
      "country": "South Africa",
      "latitude": -25.7560000,
      "longitude": 28.0750000,
      "created_at": "2023-09-21T07:28:54+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5233,
          "title": "OPBAB Coffin Sprays - Sizable \/ White Mixed Seasonal",
          "status": "delivered",
          "quantity": 1,
          "giftMessage": "",
          "productVariantId": 1173,
          "value": 1549,
          "returns": [],
        },
      ],
      "postalCode": "0008",
      "company": "OPBAB",
      "adjustments": [],
      "status": "delivered",
      "totalValue": 1608.95,
      "notes": "PO: 123-4567",
      "onPay": 1051.3100000000002,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4250",
      "name": "#BLM5072",
      "firstName": "Wegga",
      "lastName": "Pastel",
      "phone": "012 345 6789",
      "address1": "Pecanwood estate, R51 Provincial road, Broederstroom(Hartebeespoort dam) North west Provice, 0240",
      "address2": "1 The Dingemanse drive",
      "city": "Hartbesspoort dam",
      "country": "South Africa",
      "latitude": 0,
      "longitude": 0,
      "created_at": "2023-09-20T07:12:57+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5127,
          "title": "With You - Snack Box and Fresh Flowers - As Shown",
          "status": "cancel-confirmed",
          "quantity": 1,
          "giftMessage": "Happy birthday Lana.  We trust that you will have a blessed and loved year ahead.  We love you and we are proud of you.  Love mom and Oom Johan. xxxxxxxx",
          "productVariantId": 631,
          "value": 1050,
          "returns": [],
        },
      ],
      "postalCode": "0240",
      "company": null,
      "adjustments": [],
      "status": "cancel-confirmed",
      "totalValue": 1109.95,
      "notes": null,
      "onPay": 847.45,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4231",
      "name": "#BLM5053",
      "firstName": "Wegga",
      "lastName": "Pastel",
      "phone": "012 345 6789",
      "address1": "Peacanwood Estate",
      "address2": "No 1 The Dingemanse Drive",
      "city": "Hartebeespoort",
      "country": "South Africa",
      "latitude": 0,
      "longitude": 0,
      "created_at": "2023-09-19T16:46:58+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 5108,
          "title": "Joyful Moments - Small (As Shown)",
          "status": "cancelled",
          "quantity": 1,
          "giftMessage": "Liefste Lana,\r\nBaie geluk met jou verjaarsdag.  Ietsie kleins maar uit my hart. Bly die mooi Blom wat jy is. \r\nLiefde\r\nChantelle aka Bertha aka MrD ",
          "productVariantId": 594,
          "value": 495,
          "returns": [],
        },
      ],
      "postalCode": "0216",
      "company": "Hartebeespoort",
      "adjustments": [],
      "status": "cancelled",
      "totalValue": 554.95,
      "notes": null,
      "onPay": 431.20000000000005,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4073",
      "name": "#BLM4895",
      "firstName": "Suikerbos",
      "lastName": "Immacho de goudvis",
      "phone": "012 345 6789",
      "address1": "Xanadu nature estate",
      "address2": "123 muffin sparrow drive",
      "city": "Hartebeespoort",
      "country": "South Africa",
      "latitude": 0,
      "longitude": 0,
      "created_at": "2023-09-17T14:52:16+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 4936,
          "title": "Celebration Bouquet - Small \/ No",
          "status": "delivered",
          "quantity": 1,
          "giftMessage": "Baie geluk met jou verjaarsdag swes! Ons is baie lief vir jou!",
          "productVariantId": 778,
          "value": 440,
          "returns": [],
        },
      ],
      "postalCode": "0279",
      "company": null,
      "adjustments": [],
      "status": "delivered",
      "totalValue": 499.95,
      "notes": "If she is not at home you can just leave it at security and ask to phone her at 485 hawk eagle drive",
      "onPay": 389.95,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4042",
      "name": "#BLM4864",
      "firstName": "Boomtak",
      "lastName": "Moun",
      "phone": "012345678",
      "address1": "12 Bushmans Circle, Pecanwood Estate",
      "address2": null,
      "city": "Broederstroom",
      "country": "South Africa",
      "latitude": -25.7678104,
      "longitude": 27.8599664,
      "created_at": "2023-09-16T04:13:23+00:00",
      "deliveryDate": today,
      "lines": [
        {
          "id": 4904,
          "title": "Elegant Beauty - Medium (9 Roses & 3 Lilies)",
          "status": "accepted",
          "quantity": 1,
          "giftMessage": "Congratulations Leanne and Ryan! We are so happy for your growing family! We love you! ",
          "productVariantId": 1099,
          "value": 1135,
          "returns": [],
        },
      ],
      "postalCode": "0216",
      "company": null,
      "adjustments": [],
      "status": "accepted",
      "totalValue": 1194.95,
      "notes": null,
      "onPay": 911.2,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4018",
      "name": "#BLM4840",
      "firstName": "",
      "lastName": "",
      "phone": "+27 12 345 6789",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.74400,
      "longitude": 28.1960000,
      "created_at": "2023-09-15T09:38:27+00:00",
      "deliveryDate": new Date(today.getTime() - 24 * 60 * 60 * 1000),
      "lines": [
        {
          "id": 4877,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "delivered",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
        {
          "id": 4876,
          "title": "OPBAB Rose Petals",
          "status": "delivered",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Mamelodi",
      "adjustments": [],
      "status": "delivered",
      "totalValue": 1466.95,
      "notes": "PO: PO: BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
    {
      "id": "4017",
      "name": "#BLM4839",
      "firstName": "",
      "lastName": "",
      "phone": "+27 12 345 6789",
      "address1": "123 Madiba Street",
      "address2": null,
      "city": "Pretoria",
      "country": "South Africa",
      "latitude": -25.74400,
      "longitude": 28.1960000,
      "created_at": "2023-09-15T09:37:43+00:00",
      "deliveryDate": new Date(today.getTime() - 24 * 60 * 60 * 1000),
      "lines": [
        {
          "id": 4875,
          "title": "White Coffin Arrangement - Medium (As Shown)",
          "status": "delivered",
          "quantity": 1,
          "giftMessage": null,
          "productVariantId": 511,
          "value": 1049,
          "returns": [],
        },
        {
          "id": 4874,
          "title": "OPBAB Rose Petals",
          "status": "delivered",
          "quantity": 2,
          "giftMessage": null,
          "productVariantId": 876,
          "value": 179,
          "returns": [],
        },
      ],
      "postalCode": "0002",
      "company": "OPBAB Mamelodi",
      "adjustments": [],
      "status": "delivered",
      "totalValue": 1466.95,
      "notes": "PO: PO:BB1234",
      "onPay": 960.4300000000003,
      "deliveryFee": "59.95",
      "deliveryCost": "59.95",
    },
  ],
  "links": {
    "first": "http:\/\/localhost:1999\/api\/orders?page=1",
    "last": "http:\/\/localhost:1999\/api\/orders?page=7",
    "prev": null,
    "next": "http:\/\/localhost:1999\/api\/orders?page=2",
  },
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 7,
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=1",
        "label": "1",
        "active": true,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=2",
        "label": "2",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=3",
        "label": "3",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=4",
        "label": "4",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=5",
        "label": "5",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=6",
        "label": "6",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=7",
        "label": "7",
        "active": false,
      },
      {
        "url": "http:\/\/localhost:1999\/api\/orders?page=2",
        "label": "Next &raquo;",
        "active": false,
      },
    ],
    "path": "http:\/\/localhost:1999\/api\/orders",
    "per_page": 15,
    "to": 15,
    "total": 93,
  },
};
