export const demoResponseProduct: { [key: number]: object; } = {
  222: {
    "data": {
      "id": 222,
      "title": "Medium (As Shown)",
      "product": {
        "id": 59,
        "title": "Country Basket",
        "slug": "country-basket",
        "description": "<meta charset=\"utf-8\">\n<p><strong>A beautiful soft arrangement with pastel, seasonal flowers. The perfect floral gift.<\/strong><\/p>\n<p>Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website.<\/p>\n<p>Because your order is coming from a local florist your vase or container may look different from the display image depending on the availability in your recipient\u2019s delivery area.<\/p>\n<p><span>Thank you for supporting local South African florists. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 713,
          "altText": "Country Basket Small Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/country-basket-936263.jpg?v=1689770562",
        }],
        "variants": [{ "id": 221, "title": "Small", "sku": "0046S" }, {
          "id": 222,
          "title": "Medium (As Shown)",
          "sku": "0046M",
        }, { "id": 224, "title": "Extra Large", "sku": "0046XL" }, { "id": 223, "title": "Large", "sku": "0046L" }],
      },
      "component_rates": [{
        "id": 1250,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1251,
        "quantity": 3,
        "component_rate": {
          "id": 54,
          "component": {
            "id": 5,
            "name": "Pink Alstroemeria",
            "slug": "pink-alstroemeria",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1252,
        "quantity": 1,
        "component_rate": {
          "id": 313,
          "component": {
            "id": 292,
            "name": "Medium Basket",
            "slug": "medium-basket",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1253,
        "quantity": 3,
        "component_rate": {
          "id": 323,
          "component": {
            "id": 274,
            "name": "Pink Chrysanthemums",
            "slug": "pink-chrysanthemums",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1254,
        "quantity": 8,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1255,
        "quantity": 4,
        "component_rate": {
          "id": 146,
          "component": {
            "id": 114,
            "name": "Purple Limonium",
            "slug": "purple-limonium",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 14, "name": "Purple" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1257,
        "quantity": 6,
        "component_rate": {
          "id": 211,
          "component": {
            "id": 188,
            "name": "Pink Roses",
            "slug": "pink-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1258,
        "quantity": 10,
        "component_rate": {
          "id": 298,
          "component": {
            "id": 231,
            "name": "Pink Sweet William",
            "slug": "pink-sweet-william",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 37, "name": "1 Stem" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1259,
        "quantity": 1,
        "component_rate": {
          "id": 312,
          "component": {
            "id": 285,
            "name": "Plastic Bowl Small",
            "slug": "plastic-bowl-small",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 9, "name": "1 Small" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  440: {
    "data": {
      "id": 440,
      "title": "Small (As Shown)",
      "product": {
        "id": 130,
        "title": "Delightful Posy",
        "slug": "delightful-posy",
        "description": "<meta charset=\"utf-8\">\n<p><strong>Our Delightful Posy Arrangement is a beautiful gift to bring happiness and joy to someone's life. Orange, Purple and Pink flowers arranged with care make for a very warm and happy floral arrangement.\u00a0<\/strong><\/p>\n<p>Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website.<\/p>\n<p>Because your order is coming from a local florist your vase or container may look different from the display image depending on the availability in your recipient\u2019s delivery area.<\/p>\n<p><span>Thank you for supporting local South African florists in our beautiful country. #SupportLocal<\/span><\/p>\n<p>\u00a0<\/p>",
        "images": [{
          "id": 742,
          "altText": "Delightful Posy Small (As Shown) Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/delightful-posy-465155.jpg?v=1689770584",
        }],
        "variants": [{ "id": 440, "title": "Small (As Shown)", "sku": "0120" }],
      },
      "component_rates": [{
        "id": 1506,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1522,
        "quantity": 3,
        "component_rate": {
          "id": 326,
          "component": {
            "id": 310,
            "name": "Orange Alstromeria",
            "slug": "orange-alstromeria",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 7, "name": "Orange" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1523,
        "quantity": 2,
        "component_rate": {
          "id": 260,
          "component": {
            "id": 273,
            "name": "Purple Chrysanthemums",
            "slug": "purple-chrysanthemums",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 14, "name": "Purple" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1524,
        "quantity": 1,
        "component_rate": {
          "id": 327,
          "component": {
            "id": 267,
            "name": "Plastic Container 24Cm",
            "slug": "plastic-container-24cm",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 14, "name": "1 cm" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1525,
        "quantity": 1,
        "component_rate": {
          "id": 127,
          "component": {
            "id": 95,
            "name": "Kraft Paper",
            "slug": "kraft-paper",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1526,
        "quantity": 4,
        "component_rate": {
          "id": 136,
          "component": {
            "id": 104,
            "name": "Leather Leaf",
            "slug": "leather-leaf",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1527,
        "quantity": 1,
        "component_rate": {
          "id": 314,
          "component": {
            "id": 298,
            "name": "Medium Oasis",
            "slug": "medium-oasis",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1528,
        "quantity": 5,
        "component_rate": {
          "id": 210,
          "component": {
            "id": 190,
            "name": "Orange Roses",
            "slug": "orange-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 7, "name": "Orange" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1529,
        "quantity": 3,
        "component_rate": {
          "id": 18,
          "component": {
            "id": 225,
            "name": "Pink Statice",
            "slug": "pink-statice",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 1, "name": "pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1530,
        "quantity": 1,
        "component_rate": {
          "id": 214,
          "component": {
            "id": 228,
            "name": "String",
            "slug": "string",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1531,
        "quantity": 4,
        "component_rate": {
          "id": 328,
          "component": {
            "id": 253,
            "name": "Viburnum",
            "slug": "viburnum",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": false,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  511: {
    "data": {
      "id": 511,
      "title": "Medium (As Shown)",
      "product": {
        "id": 163,
        "title": "White Coffin Arrangement",
        "slug": "white-coffin-arrangement",
        "description": "<meta charset=\"utf-8\">\n<p>This Casket Spray of traditional whites and greens is a peaceful and loving memorial arrangement in a classical and graceful style.<\/p>\n<p>Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website.<\/p>\n<p><span>Thank you for supporting local South African florists. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 1026,
          "altText": "White Coffin Arrangement Small Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/white-coffin-arrangement-482403.jpg?v=1689770993",
        }],
        "variants": [{ "id": 510, "title": "Small", "sku": "0155S" }, {
          "id": 511,
          "title": "Medium (As Shown)",
          "sku": "0155M",
        }, { "id": 512, "title": "Large", "sku": "0155L" }, { "id": 513, "title": "Extra Large", "sku": "0155Xl" }],
      },
      "component_rates": [{
        "id": 2399,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2400,
        "quantity": 6,
        "component_rate": {
          "id": 52,
          "component": {
            "id": 3,
            "name": "White Alstroemeria",
            "slug": "white-alstroemeria",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2401,
        "quantity": 9,
        "component_rate": {
          "id": 101,
          "component": {
            "id": 70,
            "name": "White Gerbera",
            "slug": "white-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2402,
        "quantity": 8,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2403,
        "quantity": 2,
        "component_rate": {
          "id": 119,
          "component": {
            "id": 87,
            "name": "Gypsophila",
            "slug": "gypsophila",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2404,
        "quantity": 1,
        "component_rate": {
          "id": 334,
          "component": {
            "id": 177,
            "name": "Rectangle Tray Medium",
            "slug": "rectangle-tray-medium",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2405,
        "quantity": 3,
        "component_rate": {
          "id": 168,
          "component": {
            "id": 136,
            "name": "White Lisianthus",
            "slug": "white-lisianthus",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2406,
        "quantity": 2,
        "component_rate": {
          "id": 314,
          "component": {
            "id": 298,
            "name": "Medium Oasis",
            "slug": "medium-oasis",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2407,
        "quantity": 10,
        "component_rate": {
          "id": 206,
          "component": {
            "id": 187,
            "name": "White Roses",
            "slug": "white-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2408,
        "quantity": 2,
        "component_rate": {
          "id": 4,
          "component": {
            "id": 209,
            "name": "Single Tray",
            "slug": "single-tray",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 2409,
        "quantity": 8,
        "component_rate": {
          "id": 26,
          "component": {
            "id": 222,
            "name": "St. Josephs",
            "slug": "st-josephs",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 48, "name": "1 Stem (Multi Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  577: {
    "data": {
      "id": 577,
      "title": "Large (As Shown) \/ No",
      "product": {
        "id": 201,
        "title": "Colour Me Happy",
        "slug": "colour-me-happy",
        "description": "<meta charset=\"utf-8\">\n<p><b>Send happiness with a kaleidoscope of bright flowers including pink snapdragons, lilac chrysanthemums, orange roses, pink lilies, orange cockscomb, blue delphinium and purple statice delivered with a box of (200g) Ferrero Rocher chocolate.<\/b><\/p>\n<p><span>Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website. Thank you for supporting local South African florists in our beautiful country. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 704,
          "altText": "Colour Me Happy Large (As Shown) Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/colour-me-happy-921688.jpg?v=1689770559",
        }],
        "variants": [{ "id": 577, "title": "Large (As Shown) \/ No", "sku": "0195L" }, {
          "id": 578,
          "title": "Large (As Shown) \/ Yes",
          "sku": "0195L-V",
        }],
      },
      "component_rates": [{
        "id": 1196,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1197,
        "quantity": 5,
        "component_rate": {
          "id": 54,
          "component": {
            "id": 5,
            "name": "Pink Alstroemeria",
            "slug": "pink-alstroemeria",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1198,
        "quantity": 5,
        "component_rate": {
          "id": 311,
          "component": {
            "id": 290,
            "name": "Lilac Chrysanthemum",
            "slug": "lilac-chrysanthemum",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 5, "name": "Lilac" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1199,
        "quantity": 5,
        "component_rate": {
          "id": 310,
          "component": {
            "id": 289,
            "name": "Blue Delphinium",
            "slug": "blue-delphinium",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 30, "name": "1 SIngle" },
            "colour": { "id": 24, "name": "Blue" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1200,
        "quantity": 1,
        "component_rate": {
          "id": 49,
          "component": {
            "id": 58,
            "name": "Ferrero Rocher (16 Balls)",
            "slug": "ferrero-rocher-16-balls",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 5, "name": "200 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1201,
        "quantity": 10,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1202,
        "quantity": 3,
        "component_rate": {
          "id": 127,
          "component": {
            "id": 95,
            "name": "Kraft Paper",
            "slug": "kraft-paper",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1203,
        "quantity": 10,
        "component_rate": {
          "id": 210,
          "component": {
            "id": 190,
            "name": "Orange Roses",
            "slug": "orange-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 7, "name": "Orange" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1204,
        "quantity": 5,
        "component_rate": {
          "id": 22,
          "component": {
            "id": 212,
            "name": "Pink Snapdragons",
            "slug": "pink-snapdragons",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1205,
        "quantity": 1,
        "component_rate": {
          "id": 224,
          "component": {
            "id": 240,
            "name": "Twyne",
            "slug": "twyne",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1206,
        "quantity": 3,
        "component_rate": {
          "id": 322,
          "component": {
            "id": 243,
            "name": "Pink Umbellatum Lilies",
            "slug": "pink-umbellatum-lilies",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  594: {
    "data": {
      "id": 594,
      "title": "Small (As Shown)",
      "product": {
        "id": 214,
        "title": "Joyful Moments",
        "slug": "joyful-moments",
        "description": "<meta charset=\"utf-8\">\n<p><span>A playful red and pink arrangement of dahlias, gerberas, and roses, lovingly arranged by your local florist for joyful results. Send these blooms\u00a0today\u00a0<\/span><span>and get\u00a0ready for joyful moments.<\/span><\/p>\n<p>Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website.<\/p>\n<p><span>Thank you for supporting local South African florists. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 817,
          "altText": "Joyful Moments Small (As Shown) Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/joyful-moments-315107.jpg?v=1689770697",
        }],
        "variants": [{ "id": 594, "title": "Small (As Shown)", "sku": "0210" }],
      },
      "component_rates": [{
        "id": 3367,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3368,
        "quantity": 2,
        "component_rate": {
          "id": 85,
          "component": {
            "id": 49,
            "name": "Pink Dahlia",
            "slug": "pink-dahlia",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3369,
        "quantity": 2,
        "component_rate": {
          "id": 103,
          "component": {
            "id": 72,
            "name": "Red Gerbera",
            "slug": "red-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 21, "name": "Red" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3370,
        "quantity": 4,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3371,
        "quantity": 1,
        "component_rate": {
          "id": 166,
          "component": {
            "id": 134,
            "name": "Pink Lisianthus",
            "slug": "pink-lisianthus",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3372,
        "quantity": 3,
        "component_rate": {
          "id": 229,
          "component": {
            "id": 185,
            "name": "Red Roses",
            "slug": "red-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 21, "name": "Red" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3373,
        "quantity": 1,
        "component_rate": {
          "id": 8,
          "component": {
            "id": 205,
            "name": "Pink Scabiosa",
            "slug": "pink-scabiosa",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 8, "name": "Pink" },
            "hasImage": false,
          },
        },
      }, {
        "id": 3374,
        "quantity": 1,
        "component_rate": {
          "id": 20,
          "component": {
            "id": 219,
            "name": "Square Vase 12x12",
            "slug": "square-vase-12x12",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 14, "name": "1 cm" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  631: {
    "data": {
      "id": 631,
      "title": "As Shown",
      "product": {
        "id": 250,
        "title": "With You - Snack Box and Fresh Flowers",
        "slug": "with-you-snack-box-and-fresh-flowers",
        "description": "<meta charset=\"utf-8\">\n<p dir=\"ltr\"><span>Send a gift that\u2019s sure to touch their heart and lift their spirits when you surprise them with this beautiful, fresh floral arrangement, accompanied by a box of assorted, decadent treats. Packed with all the healthy protein and good fats found in cashews, almonds and mixed nuts, this snack gift selection also includes a few indulgent chocolate and caramel treats to satisfy their sweet tooth.\u00a0<\/span><\/p>\n<ul>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Fresh Floral Arrangement\u00a0<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Lindt Chocolate Slab<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Lindt Lindor<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Cream Caramels<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Cashews 100g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Almonds 100g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Mixed Nuts 100g<\/span><\/p>\n<\/li>\n<\/ul>\n<p dir=\"ltr\"><span>Because your order is coming from a local florist your products the container may look different from the display image depending on the availability in your recipient\u2019s delivery area. Thank you for supporting local South African florists in our beautiful country. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 1038,
          "altText": "With You - Snack Box and Fresh Flowers As Shown Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/with-you-snack-box-and-fresh-flowers-144510.png?v=1689771006",
        }],
        "variants": [{ "id": 631, "title": "As Shown", "sku": "0246" }],
      },
      "component_rates": [{
        "id": 1720,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1721,
        "quantity": 1,
        "component_rate": {
          "id": 42,
          "component": {
            "id": 29,
            "name": "Cardboard Box 30x30CM",
            "slug": "cardboard-box-30x30cm",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 14, "name": "1 cm" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1722,
        "quantity": 1,
        "component_rate": {
          "id": 152,
          "component": {
            "id": 120,
            "name": "Lindt Excellence",
            "slug": "lindt-excellence",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1723,
        "quantity": 1,
        "component_rate": {
          "id": 158,
          "component": {
            "id": 126,
            "name": "Lindt Lindor Irresistibly Smooth Milk Chocolate Truffles Box",
            "slug": "lindt-lindor-irresistibly-smooth-milk-chocolate-truffles-box",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 12, "name": "37 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1724,
        "quantity": 1,
        "component_rate": {
          "id": 304,
          "component": {
            "id": 295,
            "name": "Almonds 100g",
            "slug": "almonds-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1725,
        "quantity": 1,
        "component_rate": {
          "id": 305,
          "component": {
            "id": 296,
            "name": "Cashews 100g",
            "slug": "cashews-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1726,
        "quantity": 1,
        "component_rate": {
          "id": 225,
          "component": {
            "id": 270,
            "name": "Mixed nuts 100g",
            "slug": "mixed-nuts-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1727,
        "quantity": 3,
        "component_rate": {
          "id": 27,
          "component": {
            "id": 226,
            "name": "Straw (Wood Wool)",
            "slug": "straw-wood-wool",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5347,
        "quantity": 1,
        "component_rate": {
          "id": 426,
          "component": {
            "id": 342,
            "name": "Small White Glass Vase Arrangement",
            "slug": "small-white-glass-vase-arrangement",
            "container": true,
            "exclude_auto_calculations": false,
            "show_on_menu": false,
            "unit": { "id": 9, "name": "1 Small" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  778: {
    "data": {
      "id": 778,
      "title": "Small \/ No",
      "product": {
        "id": 279,
        "title": "Celebration Bouquet",
        "slug": "celebration-bouquet",
        "description": "<meta charset=\"utf-8\">\n<p><b>A gift means so much more when it\u2019s straight from the heart. This stunning bouquet of passionate pinks, purples and oranges are expertly arranged and perfect for any celebration. It\u2019s a surprise that speaks volumes and sends happiness.<\/b><\/p>\n<p>Cut flower stems included in this beautiful creation may differ slightly subject to seasonal and flower market availability. Our team will inform you if there are any major changes and we\u2019ll do our best to ensure that it looks like what you see on our website. Thank you for supporting local South African florists. #SupportLocal<\/p>",
        "images": [{
          "id": 695,
          "altText": "Celebration Bouquet Small Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/celebration-bouquet-500585.jpg?v=1689770547",
        }],
        "variants": [{ "id": 785, "title": "Extra Large \/ Yes", "sku": "0087XL-V" }, {
          "id": 779,
          "title": "Small \/ Yes",
          "sku": "0087S-V",
        }, { "id": 781, "title": "Medium (As Shown) \/ Yes", "sku": "0087M-V" }, {
          "id": 780,
          "title": "Medium (As Shown) \/ No",
          "sku": "0087M",
        }, { "id": 782, "title": "Large \/ No", "sku": "0087L" }, {
          "id": 784,
          "title": "Extra Large \/ No",
          "sku": "0087XL",
        }, { "id": 783, "title": "Large \/ Yes", "sku": "0087L-V" }, {
          "id": 778,
          "title": "Small \/ No",
          "sku": "0087S",
        }],
      },
      "component_rates": [{
        "id": 12,
        "quantity": 2,
        "component_rate": {
          "id": 38,
          "component": {
            "id": 44,
            "name": "Chrysanthemum",
            "slug": "chrysanthemum",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 13,
        "quantity": 1,
        "component_rate": {
          "id": 87,
          "component": {
            "id": 51,
            "name": "Decorative Tissue Paper",
            "slug": "decorative-tissue-paper",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 14,
        "quantity": 2,
        "component_rate": {
          "id": 106,
          "component": {
            "id": 75,
            "name": "Orange Gerbera",
            "slug": "orange-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 7, "name": "Orange" },
            "hasImage": false,
          },
        },
      }, {
        "id": 15,
        "quantity": 2,
        "component_rate": {
          "id": 104,
          "component": {
            "id": 73,
            "name": "Cerise Gerbera",
            "slug": "cerise-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 11, "name": "Cerise" },
            "hasImage": false,
          },
        },
      }, {
        "id": 16,
        "quantity": 7,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 17,
        "quantity": 1,
        "component_rate": {
          "id": 209,
          "component": {
            "id": 182,
            "name": "Ribbon",
            "slug": "ribbon",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 18,
        "quantity": 2,
        "component_rate": {
          "id": 146,
          "component": {
            "id": 114,
            "name": "Purple Limonium",
            "slug": "purple-limonium",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 14, "name": "Purple" },
            "hasImage": false,
          },
        },
      }, {
        "id": 19,
        "quantity": 6,
        "component_rate": {
          "id": 210,
          "component": {
            "id": 190,
            "name": "Orange Roses",
            "slug": "orange-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 7, "name": "Orange" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  822: {
    "data": {
      "id": 822,
      "title": "As Shown",
      "product": {
        "id": 306,
        "title": "Biltong and Nuts Snack Box",
        "slug": "biltong-and-nuts-snack-box",
        "description": "<meta charset=\"utf-8\">\n<p dir=\"ltr\"><span>This inviting biltong and nuts snack gift box will get your savoury-loving recipient\u2019s mouth-watering. An assortment of luxury nuts, including cashews, almonds and mixed nut selection, is paired with succulent, sliced biltong and delicious dried wors, to create a snack sensation!<\/span><\/p>\n<ul>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Biltong 150g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Droe Wors 150g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Almonds 100g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Cashews 100g<\/span><\/p>\n<\/li>\n<li dir=\"ltr\">\n<p role=\"presentation\" dir=\"ltr\"><span>Mixed Nuts 100g<\/span><\/p>\n<\/li>\n<\/ul>\n<p>Because your order is coming from a local florist your products the container may look different from the display image depending on the availability in your recipient\u2019s delivery area.<\/p>\n<p dir=\"ltr\"><span>Thank you for supporting local South African florists in our beautiful country. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 661,
          "altText": "Biltong and Nuts Snack Box As Shown Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/biltong-and-nuts-snack-box-374650.png?v=1689770513",
        }],
        "variants": [{ "id": 822, "title": "As Shown", "sku": "0242" }],
      },
      "component_rates": [{
        "id": 496,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 497,
        "quantity": 5,
        "component_rate": {
          "id": 73,
          "component": {
            "id": 22,
            "name": "Brown Packet for Biltong or Sweets",
            "slug": "brown-packet-for-biltong-or-sweets",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 498,
        "quantity": 1,
        "component_rate": {
          "id": 42,
          "component": {
            "id": 29,
            "name": "Cardboard Box 30x30CM",
            "slug": "cardboard-box-30x30cm",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 14, "name": "1 cm" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 499,
        "quantity": 1,
        "component_rate": {
          "id": 68,
          "component": {
            "id": 18,
            "name": "Biltong 150g",
            "slug": "biltong-150g",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 11, "name": "150 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 500,
        "quantity": 1,
        "component_rate": {
          "id": 92,
          "component": {
            "id": 56,
            "name": "Droe Wors",
            "slug": "droe-wors",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 11, "name": "150 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 501,
        "quantity": 1,
        "component_rate": {
          "id": 225,
          "component": {
            "id": 270,
            "name": "Mixed nuts 100g",
            "slug": "mixed-nuts-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 502,
        "quantity": 1,
        "component_rate": {
          "id": 27,
          "component": {
            "id": 226,
            "name": "Straw (Wood Wool)",
            "slug": "straw-wood-wool",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 507,
        "quantity": 1,
        "component_rate": {
          "id": 41,
          "component": {
            "id": 41,
            "name": "Cellophane Wrapping Sheet 1m",
            "slug": "cellophane-wrapping-sheet-1m",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 508,
        "quantity": 1,
        "component_rate": {
          "id": 209,
          "component": {
            "id": 182,
            "name": "Ribbon",
            "slug": "ribbon",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1116,
        "quantity": 1,
        "component_rate": {
          "id": 304,
          "component": {
            "id": 295,
            "name": "Almonds 100g",
            "slug": "almonds-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 1117,
        "quantity": 1,
        "component_rate": {
          "id": 305,
          "component": {
            "id": 296,
            "name": "Cashews 100g",
            "slug": "cashews-100g",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 10, "name": "100 g" },
            "colour": { "id": 17, "name": "Brown" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  876: {
    "data": {
      "id": 876,
      "title": "Default Title",
      "product": {
        "id": 316,
        "title": "OPBAB Rose Petals",
        "slug": "opbab-rose-petals",
        "description": "<p><\/p>",
        "images": [{
          "id": 363,
          "altText": "",
          "height": 150,
          "width": 150,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/56c8d831-49b6-414e-92ea-6dada652e309.jpg?v=1687350935",
        }],
        "variants": [{ "id": 876, "title": "Default Title", "sku": "OPBAB99" }],
      },
      "component_rates": [{
        "id": 2457,
        "quantity": 1,
        "component_rate": {
          "id": 350,
          "component": {
            "id": 316,
            "name": "OPBAB Packet of Rose petals",
            "slug": "opbab-packet-of-rose-petals",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 30, "name": "1 SIngle" },
            "colour": { "id": 21, "name": "Red" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  1099: {
    "data": {
      "id": 1099,
      "title": "Medium (9 Roses & 3 Lilies)",
      "product": {
        "id": 489,
        "title": "Elegant Beauty",
        "slug": "elegant-beauty",
        "description": "<meta charset=\"utf-8\">\n<p><b>A luxurious, timeless and classic combination of white lilies, gerberas, roses and greenery in a glass vase will leave the receiver breathless. Arranged with love and care by your local florist.<\/b><\/p>\n<p>Cut flower stems included in this beautiful creation may differ slightly subject to seasonal and flower market availability. Our team will inform you if there are any major changes and we\u2019ll do our best to ensure that it looks like what you see on our website. Thank you for supporting local South African florists. #SupportLocal<\/p>\n<p>\u00a0<\/p>",
        "images": [{
          "id": 744,
          "altText": "Elegant Beauty Small (8 Roses & 2 Lilies) Bloomable",
          "height": 600,
          "width": 450,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/products\/elegant-beauty-306216.jpg?v=1689770585",
        }],
        "variants": [{ "id": 1100, "title": "Large (24 Roses & 4 Lilies) (As Shown)", "sku": "0090L" }, {
          "id": 1098,
          "title": "Small (8 Roses & 2 Lilies)",
          "sku": "0090S",
        }, { "id": 1099, "title": "Medium (9 Roses & 3 Lilies)", "sku": "0090M" }],
      },
      "component_rates": [{
        "id": 4539,
        "quantity": 1,
        "component_rate": {
          "id": 213,
          "component": {
            "id": 269,
            "name": "Additional Delivery fee",
            "slug": "additional-delivery-fee",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4540,
        "quantity": 4,
        "component_rate": {
          "id": 52,
          "component": {
            "id": 3,
            "name": "White Alstroemeria",
            "slug": "white-alstroemeria",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4541,
        "quantity": 3,
        "component_rate": {
          "id": 335,
          "component": {
            "id": 276,
            "name": "White Chrysanthemums",
            "slug": "white-chrysanthemums",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4542,
        "quantity": 3,
        "component_rate": {
          "id": 101,
          "component": {
            "id": 70,
            "name": "White Gerbera",
            "slug": "white-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4543,
        "quantity": 10,
        "component_rate": {
          "id": 116,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4544,
        "quantity": 6,
        "component_rate": {
          "id": 206,
          "component": {
            "id": 187,
            "name": "White Roses",
            "slug": "white-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4545,
        "quantity": 3,
        "component_rate": {
          "id": 227,
          "component": {
            "id": 186,
            "name": "Cream Roses",
            "slug": "cream-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 9, "name": "Cream" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4546,
        "quantity": 3,
        "component_rate": {
          "id": 223,
          "component": {
            "id": 246,
            "name": "Cream Umbellatum Lilies",
            "slug": "cream-umbellatum-lilies",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 9, "name": "Cream" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4547,
        "quantity": 1,
        "component_rate": {
          "id": 217,
          "component": {
            "id": 249,
            "name": "25Cm Glass vase",
            "slug": "25cm-glass-vase",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 2, "name": "Clear" },
            "hasImage": false,
          },
        },
      }, {
        "id": 4548,
        "quantity": 4,
        "component_rate": {
          "id": 212,
          "component": {
            "id": 255,
            "name": "Wax White",
            "slug": "wax-white",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }],
    },
  },
  1173: {
    "data": {
      "id": 1173,
      "title": "Sizable \/ White Mixed Seasonal",
      "product": {
        "id": 515,
        "title": "OPBAB Coffin Sprays",
        "slug": "opbab-coffin-sprays",
        "description": "<meta charset=\"utf-8\">\n<p data-mce-fragment=\"1\">This Casket Spray of traditional whites and greens is a peaceful and loving memorial arrangement in a classical and graceful style.<\/p>\n<p data-mce-fragment=\"1\">Flowers included in this beautiful creation may differ subject to seasonal and flower market availability. Our team will inform you if there are any major changes but we will do our best to ensure that it looks like what you see on our website.<\/p>\n<p data-mce-fragment=\"1\"><span data-mce-fragment=\"1\">Thank you for supporting local South African florists. #SupportLocal<\/span><\/p>",
        "images": [{
          "id": 616,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/whitecoffinspray.jpg?v=1688566772",
        }, {
          "id": 614,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/redandwhitecoffinspray.jpg?v=1688566772",
        }, {
          "id": 613,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/pinkandwhitecoffinspray.jpg?v=1688566772",
        }, {
          "id": 612,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/multicolouredcoffinspray.jpg?v=1688566772",
        }, {
          "id": 610,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/yellowcoffinspray.jpg?v=1688566772",
        }, {
          "id": 617,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/coffin-spray.jpg?v=1688566772",
        }, {
          "id": 615,
          "altText": "",
          "height": 1080,
          "width": 1080,
          "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0686\/5315\/4621\/files\/whitemixedseasonalcoffinspray.jpg?v=1688566772",
        }],
        "variants": [{ "id": 1161, "title": "Small \/ White Mixed Seasonal", "sku": "OPBAB116" }, {
          "id": 1163,
          "title": "Small \/ Red and White",
          "sku": "OPBAB118",
        }, { "id": 1166, "title": "Small \/ White", "sku": "OPBAB121" }, {
          "id": 1164,
          "title": "Small \/ Pink and White",
          "sku": "OPBAB119",
        }, { "id": 1165, "title": "Small \/ Multi Coloured", "sku": "OPBAB120" }, {
          "id": 1162,
          "title": "Small \/ Yellow",
          "sku": "OPBAB117",
        }, { "id": 1167, "title": "Medium \/ White Mixed Seasonal", "sku": "OPBAB122" }, {
          "id": 1175,
          "title": "Sizable \/ Red and White",
          "sku": "OPBAB130",
        }, { "id": 1173, "title": "Sizable \/ White Mixed Seasonal", "sku": "OPBAB128" }, {
          "id": 1169,
          "title": "Medium \/ Red and White",
          "sku": "OPBAB124",
        }, { "id": 1183, "title": "Large \/ White", "sku": "OPBAB139" }, {
          "id": 1179,
          "title": "Large \/ Yellow",
          "sku": "OPBAB135",
        }, { "id": 1177, "title": "Sizable \/ Multi Coloured", "sku": "OPBAB132" }, {
          "id": 1172,
          "title": "Medium \/ White",
          "sku": "OPBAB127",
        }, { "id": 1174, "title": "Sizable \/ Yellow", "sku": "OPBAB129" }, {
          "id": 1171,
          "title": "Medium \/ Multi Coloured",
          "sku": "OPBAB126",
        }, { "id": 1168, "title": "Medium \/ Yellow", "sku": "OPBAB123" }, {
          "id": 1178,
          "title": "Large \/ White Mixed Seasonal",
          "sku": "OPBAB134",
        }, { "id": 1176, "title": "Sizable \/ Pink and White", "sku": "OPBAB131" }, {
          "id": 1181,
          "title": "Large \/ Pink and White",
          "sku": "OPBAB137",
        }, { "id": 1170, "title": "Medium \/ Pink and White", "sku": "OPBAB125" }, {
          "id": 1180,
          "title": "Large \/ Red and White",
          "sku": "OPBAB136",
        }, { "id": 1182, "title": "Large \/ Multi Coloured", "sku": "OPBAB138" }],
      },
      "component_rates": [{
        "id": 5160,
        "quantity": 1,
        "component_rate": {
          "id": 411,
          "component": {
            "id": 340,
            "name": "Rectangle Tray Large",
            "slug": "rectangle-tray-large",
            "container": false,
            "exclude_auto_calculations": true,
            "show_on_menu": true,
            "unit": { "id": 6, "name": "1 Single" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5161,
        "quantity": 3,
        "component_rate": {
          "id": 243,
          "component": {
            "id": 151,
            "name": "Oasis",
            "slug": "oasis",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 22, "name": "1 Medium" },
            "colour": { "id": 4, "name": "Mixed" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5162,
        "quantity": 7,
        "component_rate": {
          "id": 233,
          "component": {
            "id": 222,
            "name": "St. Josephs",
            "slug": "st-josephs",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 48, "name": "1 Stem (Multi Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5163,
        "quantity": 5,
        "component_rate": {
          "id": 244,
          "component": {
            "id": 87,
            "name": "Gypsophila",
            "slug": "gypsophila",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5164,
        "quantity": 4,
        "component_rate": {
          "id": 247,
          "component": {
            "id": 70,
            "name": "White Gerbera",
            "slug": "white-gerbera",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5165,
        "quantity": 5,
        "component_rate": {
          "id": 273,
          "component": {
            "id": 3,
            "name": "White Alstroemeria",
            "slug": "white-alstroemeria",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5166,
        "quantity": 10,
        "component_rate": {
          "id": 205,
          "component": {
            "id": 187,
            "name": "White Roses",
            "slug": "white-roses",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 3, "name": "White" },
            "hasImage": false,
          },
        },
      }, {
        "id": 5167,
        "quantity": 15,
        "component_rate": {
          "id": 249,
          "component": {
            "id": 84,
            "name": "Greenery",
            "slug": "greenery",
            "container": false,
            "exclude_auto_calculations": false,
            "show_on_menu": true,
            "unit": { "id": 4, "name": "1 Stem (Single Bud)" },
            "colour": { "id": 23, "name": "Green" },
            "hasImage": false,
          },
        },
      }],
    },
  },
};
